# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pizza4Days
email: pizza@pizza4days.com
description: > # this means to ignore newlines until "baseurl:"
  A place for finding inner happiness. Find your confidence. Find your goals.
  Find your pizza4days.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://awestbro.github.io/pizza4days/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  awestbro

# Build settings
markdown: kramdown
